spring.application.name=reservation-system

spring.datasource.url=jdbc:postgresql://localhost:5432/ocean_view_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (Auto-create tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret (use a long random string in production)
jwt.secret=OceanViewSuperSecretKey2026_MinThirtyTwoChars!!
jwt.expiration=86400000